export const mockData = [
    {
        id: 1,
        title: 'Jon Smitt',
        prof: 'Project manager',
        opi: 'Professional translator with 4 years experience sdfsdfsdf ',
        imgg: '../../../public/imgTecher/man.jpg',
        twitt:'https://twitter.com/?lang=ru',
        insta: 'https://www.instagram.com/',
        link: 'https://ru.linkedin.com/',
        fack: 'https://www.facebook.com/',
    },
    {
        id: 2,
        title: 'Sara Black',
        prof: 'Developer',
        opi: 'Professional translator with 4 years experience sdfsdfsdf w23523sdfsrde ',
        imgg: '../../../public/imgTecher/man2.jpg',
        twitt:'https://twitter.com/?lang=ru',
        insta: 'https://www.instagram.com/',
        link: 'https://ru.linkedin.com/',
        fack: 'https://www.facebook.com/',
    },
    
    {
        id: 3,
        title: 'Sara Black',
        prof: 'Developer',
        opi: 'Professional translator with 4 years experience sdfsdfsdfreyeeryeryery ',
        imgg: '../../../public/imgTecher/man2.jpg',
        twitt:'https://twitter.com/?lang=ru',
        insta: 'https://www.instagram.com/',
        link: 'https://ru.linkedin.com/',
        fack: 'https://www.facebook.com/',
    },
    {
        id: 4,
        title: 'Sara Black',
        prof: 'Developer',
        opi: 'Professional translator with 4 years experience sdfsdfsdf  fhjghjghjghjghj ',
        imgg: '../../../public/imgTecher/man2.jpg',
        twitt:'https://twitter.com/?lang=ru',
        insta: 'https://www.instagram.com/',
        link: 'https://ru.linkedin.com/',
        fack: 'https://www.facebook.com/',
    },
    
]